/**
 * Auto-update check (Part A1) — notification only, never auto-downloads.
 *
 * Uses electron-updater with the `generic` provider pointed at a placeholder
 * URL. The release feed is generated by electron-builder (latest.yml) and
 * would be hosted on the real download page. Until the feed exists the check
 * fails gracefully and is logged, never shown as an error dialog.
 */
import { autoUpdater } from 'electron-updater';
import { app, dialog, type BrowserWindow } from 'electron';
import { UPDATE_FEED_URL } from '../../shared/constants';
import { isNewerVersion } from '../../shared/version';
import type { UpdateCheckResult } from '../../shared/types';
import log from '../logger';

// The feed URL is derived from the canonical repository in `shared/constants.ts`
// so a fork can never end up pointing at the upstream project's releases.
// 占位地址保护：尚未配置真实更新源时静默跳过检查，仅写日志，不打扰用户。
const isPlaceholderFeed = /example\.com|placeholder|localhost|127\.0\.0\.1/i.test(
  UPDATE_FEED_URL
);

let checking = false;

export function configureAutoUpdater(): void {
  autoUpdater.autoDownload = false; // notification only — never auto-download.
  autoUpdater.autoInstallOnAppQuit = false;
  autoUpdater.allowDowngrade = false;
  autoUpdater.setFeedURL({ provider: 'generic', url: UPDATE_FEED_URL });

  autoUpdater.on('error', (err) => {
    checking = false;
    log.warn(`[update] check failed (expected until a real feed is published): ${err.message}`);
  });
  autoUpdater.on('update-available', (info) => {
    checking = false;
    log.info(`[update] version ${info.version} is available`);
  });
  autoUpdater.on('update-not-available', () => {
    checking = false;
    log.info('[update] no update available');
  });
}

/**
 * Run a check. Returns structured info so the Settings page can render its own
 * state, and — when triggered from the tray — asks the user whether to open the
 * download page. `getWindow` is used to parent the dialog.
 */
export async function checkForUpdates(
  getWindow: () => BrowserWindow | null
): Promise<UpdateCheckResult> {
  if (checking) return { available: false, error: '正在检查中，请稍候…' };
  // 占位地址直接静默跳过，避免无意义的报错打扰用户。
  if (isPlaceholderFeed) {
    log.warn('[update] feed URL is a placeholder — skipping update check');
    return { available: false };
  }
  checking = true;
  try {
    const result = await autoUpdater.checkForUpdates();
    if (!result) {
      checking = false;
      return { available: false, error: '无法获取更新信息。' };
    }
    const info = result.updateInfo;
    const latest = info.version;
    const current = app.getVersion();
    const available = isNewerVersion(latest, current);
    checking = false;
    return { available, version: latest };
  } catch (err) {
    checking = false;
    log.warn('[update] check threw:', (err as Error).message);
    return { available: false, error: '无法连接更新服务器。' };
  }
}

/** Show the "new version" dialog; if confirmed, open the download page. */
export async function promptForUpdate(
  getWindow: () => BrowserWindow | null,
  version: string,
  onOpenDownload: () => void
): Promise<void> {
  const win = getWindow();
  const opts = {
    type: 'info' as const,
    title: '发现新版本',
    message: `新版本 (v${version}) 可用。是否打开下载页面？`,
    buttons: ['打开下载页', '取消'],
    defaultId: 0,
    cancelId: 1,
  };
  const { response } = win && !win.isDestroyed()
    ? await dialog.showMessageBox(win, opts)
    : await dialog.showMessageBox(opts);
  if (response === 0) onOpenDownload();
}
